### ISSUE TITLE
Throw error after installation

### ISSUE THREAD

**Issue by sinanyalcinkaya** [mesqueeb/vuex-easy-access#44]
===========nuxt.config.js===========
modules: [
    // Doc: https://bootstrap-vue.js.org
    'bootstrap-vue/nuxt',
    '@nuxtjs/pwa',
    // Doc: https://github.com/nuxt-community/dotenv-module
    '@nuxtjs/dotenv',
  ],

============package.json================
{
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production node server/index.js",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/dotenv": "^1.4.0",
    "@nuxtjs/pwa": "^3.0.0-0",
    "bootstrap": "^4.1.3",
    "bootstrap-vue": "^2.0.0",
    "cross-env": "^5.2.0",
    "express": "^4.16.4",
    "nuxt": "^2.0.0"
  },
  "devDependencies": {
    "nodemon": "^1.18.9",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "prettier": "^1.19.1"
  }
}

=======install command======
npm i --save vuex-easy-accesss

========Throw Error========

[nodemon] starting `node server/index.js`
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- C:\Users\tahir\Documents\tmp\nuxtjs\ornek\server\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\tahir\Documents\tmp\nuxtjs\ornek\server\index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\tahir\\Documents\\tmp\\nuxtjs\\ornek\\server\\index.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mesqueeb** [comment]
Hi! My package doesn't use 'express', so it's not related to my package.

Please try to read the error stack to define which of your packages is using express. Good luck!
